require("illico.core.options")
require("illico.core.keymaps")
require("illico.core.saveas")
require("illico.core.python")
require("illico.core.pyrun")
require("illico.core.godot")
require("illico.core.tmux_icon").setup()
