#!/usr/bin/env bash
# Pipe taskwarrior output through this to make the top task green+bold
# and completed tasks red.
# Usage: task list | colorize-top

awk '
/^--[ -]/ { print; next }
/^ID / { print; next }
/^$/ { print; next }
/tasks?$/ { print; next }
!first_done && !/^ -/ { printf "\033[1;32m%s\033[0m\n", $0; first_done=1; next }
/^ -/ { printf "\033[31m%s\033[0m\n", $0; next }
{ print }
'
