#!/usr/bin/env bash
FZF_OPTS="--layout=reverse --ansi"

# Color completed tasks (ID = -) in red
selected=$(task list rc.verbose=nothing rc._forcecolor=on 2>/dev/null | \
    awk 'NR<=1 {print; next} {if ($1 == "-") printf "\033[31m%s\033[0m\n", $0; else print}' | \
    fzf $FZF_OPTS --header-lines=1)
[ -z "$selected" ] && exit 0

# Strip ANSI codes before extracting UUID
uuid=$(echo "$selected" | sed 's/\x1b\[[0-9;]*m//g' | awk '{print $2}')

action=$(echo -e "info\ndone\nstart\nstop\nmodify\ndelete" | fzf $FZF_OPTS --prompt="action> ")
[ -z "$action" ] && exit 0

if [ "$action" = "modify" ]; then
    attr=$(echo -e "effort\npriority\nproject\ntags\ndue\ndescription\nscheduled" | fzf $FZF_OPTS --prompt="attribute> ")
    [ -z "$attr" ] && exit 0
    read -p "$attr: " value
    task "$uuid" modify "$attr:$value"
else
    task "$uuid" "$action"
fi
